In [201]:
import pandas as pd 
import numpy as np

In [202]:
df = pd.read_csv('/Users/muzafarov/Desktop/MyEducation/ML_OE/pulsar_stars_new_ex.csv')

In [203]:
df.head(10)

,MIP,STDIP,EKIP,SIP,MC,STDC,EKC,SC,TG
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0
5,93.570312,46.698114,0.531905,0.416721,1.636288,14.545074,10.621748,131.394004,0
6,119.484375,48.765059,0.031460,-0.112168,0.999164,9.279612,19.206230,479.756567,0
7,130.382812,39.844056,-0.158323,0.389540,1.220736,14.378941,13.539456,198.236457,0
8,107.250000,52.627078,0.452688,0.170347,2.331940,14.486853,9.001004,107.972506,0
9,107.257812,39.496488,0.465882,1.162877,4.079431,24.980418,7.397080,57.784738,0

In [204]:
df.shape

(17898, 9)

In [205]:
df1 = df[(df['TG'] == 0)]
df1 = df1[df1['MIP'] >= 58.2890625]
df1 = df1[df1['MIP'] <= 170.1328125]
df1

,MIP,STDIP,EKIP,SIP,MC,STDC,EKC,SC,TG
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0
...,...,...,...,...,...,...,...,...,...
17892,96.000000,44.193113,0.388674,0.281344,1.871237,15.833746,9.634927,104.821623,0
17893,136.429688,59.847421,-0.187846,-0.738123,1.296823,12.166062,15.450260,285.931022,0
17894,122.554688,49.485605,0.127978,0.323061,16.409699,44.626893,2.945244,8.297092,0
17895,119.335938,59.935939,0.159363,-0.743025,21.430602,58.872000,2.499517,4.595173,0
17896,114.507812,53.902400,0.201161,-0.024789,1.946488,13.381731,10.007967,134.238910,0

In [206]:
df2 = df[(df['TG'] == 1)]
df2 = df2[df2['MIP'] >= 8.2734375]
df2 = df2[df2['MIP'] <= 127.5703125]
df2

,MIP,STDIP,EKIP,SIP,MC,STDC,EKC,SC,TG
19,99.367188,41.572202,1.547197,4.154106,27.555184,61.719016,2.208808,3.662680,1
42,120.554688,45.549905,0.282924,0.419909,1.358696,13.079034,13.312141,212.597029,1
61,27.765625,28.666042,5.770087,37.419009,73.112876,62.070220,1.268206,1.082920,1
92,23.625000,29.948654,5.688038,35.987172,146.568562,82.394624,-0.274902,-1.121848,1
93,94.585938,35.779823,1.187309,3.687469,6.071070,29.760400,5.318767,28.698048,1
...,...,...,...,...,...,...,...,...,...
17515,89.867188,47.482295,1.591325,2.505057,0.763378,12.393561,17.940745,333.902630,1
17529,27.039062,33.754722,4.779124,26.255357,129.863712,78.815440,-0.348492,-0.893791,1
17558,77.070312,39.000638,1.884421,6.372178,38.517559,65.741059,1.589513,1.285346,1
17642,28.375000,27.649311,6.377273,45.944048,141.860368,82.893017,-0.477222,-1.067880,1
17876,111.765625,52.943585,0.671724,0.383594,149.843646,97.926948,-0.696153,-1.260403,1

In [207]:
df = pd.concat([df1, df2])
df

,MIP,STDIP,EKIP,SIP,MC,STDC,EKC,SC,TG
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0
...,...,...,...,...,...,...,...,...,...
17515,89.867188,47.482295,1.591325,2.505057,0.763378,12.393561,17.940745,333.902630,1
17529,27.039062,33.754722,4.779124,26.255357,129.863712,78.815440,-0.348492,-0.893791,1
17558,77.070312,39.000638,1.884421,6.372178,38.517559,65.741059,1.589513,1.285346,1
17642,28.375000,27.649311,6.377273,45.944048,141.860368,82.893017,-0.477222,-1.067880,1
17876,111.765625,52.943585,0.671724,0.383594,149.843646,97.926948,-0.696153,-1.260403,1

In [208]:
df['MIP'].mean()

111.13912796248455

In [209]:
df = df.sort_values(by=['SIP'])
df

,MIP,STDIP,EKIP,SIP,MC,STDC,EKC,SC,TG
2137,135.859375,81.503042,0.023921,-1.791886,3.655518,19.638924,7.228962,63.401192,0
5291,101.242188,91.808628,0.290115,-1.781888,195.795987,63.624015,-1.852570,2.544999,0
3509,113.265625,98.778911,0.179404,-1.764717,145.361204,64.773789,-0.154935,-1.374633,0
10625,141.757812,91.206475,-0.056413,-1.755332,55.243311,75.793948,1.047847,-0.255939,0
370,107.539062,86.951396,-0.008928,-1.676724,211.948997,54.010310,-2.556795,5.768458,0
...,...,...,...,...,...,...,...,...,...
4559,12.117188,28.238001,7.525028,57.175232,123.622074,68.761628,0.047999,-0.562968,1
11343,12.507812,27.597553,7.572577,58.294501,42.612876,59.377834,1.565603,1.907165,1
11589,10.320312,26.871201,7.875742,63.149537,38.887960,58.923800,1.635320,2.225703,1
10456,18.468750,24.791612,7.595097,65.385974,69.800167,75.244969,0.894922,-0.118137,1
1834,11.140625,25.695250,8.069522,68.101622,75.832776,70.894822,0.781356,-0.152781,1

In [210]:
from sklearn.model_selection import train_test_split

X = df.drop(columns='TG')
y = df['TG']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [211]:
X_train

,MIP,STDIP,EKIP,SIP,MC,STDC,EKC,SC
5972,109.898438,40.058520,0.077943,0.724209,2.237458,14.043666,10.096010,132.157564
283,20.351562,25.771711,7.024645,56.112972,70.512542,65.472305,1.102050,0.782056
1012,116.960938,47.334812,0.088199,-0.049519,3.570234,20.312095,6.922642,54.697238
4863,100.695312,41.412287,0.653801,1.511936,2.382943,16.809343,9.541324,108.375864
10120,121.101562,51.769447,-0.032285,-0.337969,1.354515,10.435648,14.924965,308.562258
...,...,...,...,...,...,...,...,...
7700,100.039062,42.904946,0.560002,1.104896,2.224916,18.220098,8.873573,83.507983
815,138.460938,52.774565,-0.009091,-0.551845,2.220736,13.204265,9.953692,139.466872
9923,107.187500,54.253708,0.283090,-0.091217,1.162207,13.871078,14.304853,218.882779
2881,126.515625,46.619970,0.077809,0.399820,1.412207,12.277783,12.606403,198.848191
3779,63.523438,36.956470,2.607135,9.659263,44.243311,63.375561,1.428222,1.258049

In [212]:
X_train['EKIP'].mean()

0.47020176259421514

In [213]:
from sklearn.preprocessing import MinMaxScaler

In [214]:
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaler = scaler.transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [215]:
X_train_scaler.T[4].mean()

0.053952955929501584

In [216]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

In [217]:
model_LR = LogisticRegression(random_state = 7)
model_LR.fit(X_train_scaler,y_train)
pred = model_LR.predict(X_test_scaler)
tn, fp, fn, tp = confusion_matrix(pred, y_test).ravel()
print(tn, fp, fn, tp)
f1_score(pred, y_test)

3209 83 10 260

0.8482871125611745

In [218]:
from sklearn.neighbors import KNeighborsClassifier

In [219]:
model_KNN = KNeighborsClassifier(n_neighbors=3)
model_KNN.fit(X_train_scaler,y_train)
pred = model_KNN.predict(X_test_scaler)
tn, fp, fn, tp = confusion_matrix(pred, y_test).ravel()
print(tn, fp, fn, tp)
f1_score(pred, y_test)

3196 52 23 291

0.8858447488584476

## Last

In [220]:
df_train = pd.read_csv('/Users/muzafarov/Desktop/MyEducation/ML_OE/MNIST_train.csv')
df_test = pd.read_csv('/Users/muzafarov/Desktop/MyEducation/ML_OE/MNIST_test.csv')

In [221]:
df_train = df_train[(df_train['label'] == 0) | (df_train['label'] == 2)]
df_test = df_test[(df_test['label'] == 0) | (df_test['label'] == 2)]

In [222]:
df_train.head(5)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [223]:
X_train = df_train.drop(columns='label')
y_train = df_train['label']

X_test = df_test.drop(columns='label')
y_test = df_test['label']

In [224]:
from sklearn.decomposition import PCA

In [225]:
pca = PCA(svd_solver='full')
pca.fit(X_train)

PCA(svd_solver='full')

In [227]:
var = pca.explained_variance_ratio_

np.where(np.cumsum(var) >= 0.83)[0][0] + 1

43

In [228]:
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)

In [230]:
X_train[12][0]

525.4304411130477

In [231]:
from sklearn.ensemble import GradientBoostingClassifier

In [232]:
model_GBC = GradientBoostingClassifier(n_estimators=500, learning_rate=0.8,max_depth=2, random_state=25).fit(X_train, y_train)

In [233]:
pred = model_GBC.predict(X_test)

In [234]:
from sklearn.metrics import classification_report

In [235]:
print(classification_report(y_test, pred, digits=4))
tn, fp, fn, tp = confusion_matrix(pred, y_test).ravel()
print(tn, fp, fn, tp)

              precision    recall  f1-score   support

           0     0.9819    0.9969    0.9894       980
           2     0.9971    0.9826    0.9898      1032

    accuracy                         0.9896      2012
   macro avg     0.9895    0.9897    0.9896      2012
weighted avg     0.9897    0.9896    0.9896      2012

977 18 3 1014

In [236]:
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [237]:
estimators = [('rf', RandomForestClassifier(random_state=25)),('svc', SVC(random_state=25))]
final_model = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression(random_state=25))

In [239]:
final_model.fit(X_train, y_train)
pred = final_model.predict(X_test)

print(classification_report(y_test, pred, digits=4))
tn, fp, fn, tp = confusion_matrix(pred, y_test).ravel()
print(tn, fp, fn, tp)

              precision    recall  f1-score   support

           0     0.9929    0.9969    0.9949       980
           2     0.9971    0.9932    0.9951      1032

    accuracy                         0.9950      2012
   macro avg     0.9950    0.9951    0.9950      2012
weighted avg     0.9950    0.9950    0.9950      2012

977 7 3 1025