In [116]:
import pandas as pd

## Пример того, как должен выглядеть ответ

In [117]:
df_example = pd.read_csv('trainee_example.csv')
df_example

   Unnamed: 0   im
0           0  0.0
1           1  0.0
2           2  1.0
3           3  1.0

In [118]:
df_train = pd.read_csv('trainee_train.csv')
df_train

,Unnamed: 0,im,v1,v2,v3,v4,v5,v6,v7,v8,...,v437,v438,v439,v440,v441,v442,v443,v444,v445,v446
0,0,0.0,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,129.854839,129.828431,...,128.800985,128.232694,128.211893,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
1,1,1.0,128.100243,128.157072,126.636364,128.273006,130.810403,129.023232,128.633333,128.994152,...,128.914365,128.232694,128.211893,128.167519,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
2,2,1.0,128.100243,128.157072,129.255102,128.273006,130.810403,129.023232,126.769231,126.926295,...,128.800985,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,125.274194
3,3,1.0,128.100243,128.157072,127.630027,128.273006,126.532819,129.023232,126.769231,126.926295,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
4,4,1.0,128.100243,128.336364,129.255102,128.273006,130.810403,126.042980,129.854839,126.926295,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,611,0.0,128.100243,128.157072,129.255102,128.273006,130.810403,129.023232,129.854839,129.828431,...,128.800985,128.232694,128.211893,126.744108,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
612,612,1.0,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,126.769231,126.926295,...,128.800985,128.232694,128.211893,126.744108,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
613,613,1.0,130.798507,131.174905,129.255102,117.900000,132.860465,130.381148,129.854839,129.828431,...,128.914365,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,126.611554
614,614,1.0,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,129.854839,126.926295,...,128.800985,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,130.477398,130.496150
615,615,1.0,128.100243,128.157072,126.636364,128.273006,126.532819,129.023232,128.633333,128.994152,...,128.800985,128.232694,128.211893,128.167519,126.100000,127.709786,127.349282,127.329412,130.477398,130.496150

In [119]:
df_test = pd.read_csv('trainee_test_fish.csv')
df_test

,Unnamed: 0,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v437,v438,v439,v440,v441,v442,v443,v444,v445,v446
0,0,130.798507,131.174905,129.255102,132.199234,128.746479,130.381148,129.854839,129.828431,129.868526,...,128.800985,128.232694,128.211893,128.167519,126.100000,127.709786,127.349282,127.063052,127.825000,126.611554
1,1,128.100243,128.157072,127.630027,128.273006,130.810403,129.023232,126.769231,126.926295,127.196460,...,128.800985,130.794007,127.750000,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
2,2,128.100243,128.157072,129.255102,128.273006,130.810403,126.042980,129.854839,129.828431,129.868526,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
3,3,130.798507,131.174905,129.255102,132.199234,132.860465,130.381148,129.854839,129.828431,129.868526,...,126.503759,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,127.825000,126.611554
4,4,130.798507,131.174905,129.255102,132.199234,130.810403,130.381148,129.854839,129.828431,129.868526,...,128.914365,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,126.611554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,211,130.798507,131.174905,129.255102,117.900000,132.860465,130.381148,129.854839,129.828431,129.868526,...,128.914365,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,127.825000,126.611554
212,212,128.100243,128.157072,126.636364,128.273006,130.810403,129.023232,128.633333,128.994152,128.994152,...,128.800985,128.232694,128.211893,126.744108,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
213,213,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,127.720000,127.428571,127.428571,...,128.914365,128.232694,128.211893,128.167519,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
214,214,128.100243,128.157072,129.255102,128.273006,126.532819,126.042980,129.854839,129.828431,129.868526,...,128.914365,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,130.477398,130.496150
215,215,128.100243,128.157072,127.630027,128.273006,126.532819,129.023232,129.854839,126.926295,127.196460,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150

In [120]:
describe = df_train.describe()
describe = describe.drop(columns=['im', 'Unnamed: 0'])
describe

,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,...,v437,v438,v439,v440,v441,v442,v443,v444,v445,v446
count,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000,...,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000,616.000000
mean,128.609606,128.603800,128.660703,128.523063,128.410981,128.610633,128.636522,128.688810,128.761940,128.690394,...,128.645251,128.532595,128.544489,128.514329,128.514597,128.491559,128.496883,128.459309,128.488060,128.478922
std,1.019311,1.059058,0.938667,2.291477,2.232095,1.578053,1.359686,1.332505,1.249895,1.053749,...,0.685546,0.823381,0.968617,1.358473,1.658867,1.596935,1.965948,1.862891,2.284923,2.158584
min,128.100243,127.666667,126.636364,113.000000,126.532819,126.042980,126.769231,126.926295,127.196460,125.000000,...,126.503759,128.232694,127.750000,120.000000,126.100000,125.223301,125.535433,127.063052,125.169118,125.274194
25%,128.100243,128.157072,127.630027,128.273006,126.532819,129.023232,126.769231,126.926295,127.196460,128.618063,...,128.800985,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,126.611554
50%,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,129.854839,129.828431,129.868526,128.618063,...,128.800985,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,130.477398,130.496150
75%,128.100243,128.157072,129.255102,128.273006,130.810403,129.023232,129.854839,129.828431,129.868526,128.618063,...,128.914365,128.232694,128.211893,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
max,130.798507,131.174905,129.267241,132.199234,132.860465,136.222222,129.854839,129.828431,129.868526,130.917969,...,129.252747,130.794007,132.000000,130.512476,130.411160,130.650165,134.210526,131.017268,130.666667,130.496150

In [121]:
describe.loc['max'].max()

143.5

In [122]:
describe.loc['min'].min()

113.0

In [123]:
df_train.head(5)

,Unnamed: 0,im,v1,v2,v3,v4,v5,v6,v7,v8,...,v437,v438,v439,v440,v441,v442,v443,v444,v445,v446
0,0,0.0,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,129.854839,129.828431,...,128.800985,128.232694,128.211893,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
1,1,1.0,128.100243,128.157072,126.636364,128.273006,130.810403,129.023232,128.633333,128.994152,...,128.914365,128.232694,128.211893,128.167519,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
2,2,1.0,128.100243,128.157072,129.255102,128.273006,130.810403,129.023232,126.769231,126.926295,...,128.800985,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,125.274194
3,3,1.0,128.100243,128.157072,127.630027,128.273006,126.532819,129.023232,126.769231,126.926295,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
4,4,1.0,128.100243,128.336364,129.255102,128.273006,130.810403,126.042980,129.854839,126.926295,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150

In [124]:
df_train = df_train.drop(columns='Unnamed: 0')
df_train.head(5)

,im,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v437,v438,v439,v440,v441,v442,v443,v444,v445,v446
0,0.0,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,129.854839,129.828431,129.868526,...,128.800985,128.232694,128.211893,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
1,1.0,128.100243,128.157072,126.636364,128.273006,130.810403,129.023232,128.633333,128.994152,128.994152,...,128.914365,128.232694,128.211893,128.167519,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
2,1.0,128.100243,128.157072,129.255102,128.273006,130.810403,129.023232,126.769231,126.926295,127.196460,...,128.800985,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,125.274194
3,1.0,128.100243,128.157072,127.630027,128.273006,126.532819,129.023232,126.769231,126.926295,127.196460,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
4,1.0,128.100243,128.336364,129.255102,128.273006,130.810403,126.042980,129.854839,126.926295,127.196460,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150

In [125]:
X = df_train.drop(columns='im')
y = df_train['im']

In [126]:
X

,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,...,v437,v438,v439,v440,v441,v442,v443,v444,v445,v446
0,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,129.854839,129.828431,129.868526,128.618063,...,128.800985,128.232694,128.211893,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
1,128.100243,128.157072,126.636364,128.273006,130.810403,129.023232,128.633333,128.994152,128.994152,128.618063,...,128.914365,128.232694,128.211893,128.167519,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
2,128.100243,128.157072,129.255102,128.273006,130.810403,129.023232,126.769231,126.926295,127.196460,128.618063,...,128.800985,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,125.274194
3,128.100243,128.157072,127.630027,128.273006,126.532819,129.023232,126.769231,126.926295,127.196460,127.433333,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
4,128.100243,128.336364,129.255102,128.273006,130.810403,126.042980,129.854839,126.926295,127.196460,128.618063,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,128.100243,128.157072,129.255102,128.273006,130.810403,129.023232,129.854839,129.828431,129.868526,128.618063,...,128.800985,128.232694,128.211893,126.744108,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
612,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,126.769231,126.926295,127.196460,128.618063,...,128.800985,128.232694,128.211893,126.744108,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
613,130.798507,131.174905,129.255102,117.900000,132.860465,130.381148,129.854839,129.828431,129.868526,130.917969,...,128.914365,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,126.611554
614,128.100243,128.157072,129.255102,128.273006,126.532819,129.023232,129.854839,126.926295,127.196460,128.618063,...,128.800985,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,130.477398,130.496150
615,128.100243,128.157072,126.636364,128.273006,126.532819,129.023232,128.633333,128.994152,128.994152,128.618063,...,128.800985,128.232694,128.211893,128.167519,126.100000,127.709786,127.349282,127.329412,130.477398,130.496150

In [127]:
from sklearn.preprocessing import MinMaxScaler

In [128]:
scaler = MinMaxScaler()
X_scaler = scaler.fit_transform(X)

In [129]:
X_scaler = pd.DataFrame(data=X_scaler)
X_scaler

,0,1,2,3,4,5,6,7,8,9,...,436,437,438,439,440,441,442,443,444,445
0,0.0,0.139787,0.995386,0.795501,0.000000,0.292777,1.000000,1.000000,1.000000,0.611369,...,0.835662,0.0,0.108681,1.000000,1.000000,1.000000,0.618927,1.000000,0.965572,1.000000
1,0.0,0.139787,0.000000,0.795501,0.676015,0.292777,0.604128,0.712529,0.672772,0.611369,...,0.876906,0.0,0.108681,0.776936,1.000000,1.000000,0.618927,1.000000,0.965572,1.000000
2,0.0,0.139787,0.995386,0.795501,0.676015,0.292777,0.000000,0.000000,0.000000,0.611369,...,0.835662,0.0,0.108681,0.776936,0.452714,0.458181,0.209087,0.000000,0.000000,0.000000
3,0.0,0.139787,0.377693,0.795501,0.000000,0.292777,0.000000,0.000000,0.000000,0.411177,...,0.835662,1.0,0.770852,1.000000,1.000000,1.000000,0.618927,1.000000,0.965572,1.000000
4,0.0,0.190893,0.995386,0.795501,0.676015,0.000000,1.000000,0.000000,0.000000,0.611369,...,0.835662,1.0,0.770852,1.000000,1.000000,1.000000,0.618927,1.000000,0.965572,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,0.0,0.139787,0.995386,0.795501,0.676015,0.292777,1.000000,1.000000,1.000000,0.611369,...,0.835662,0.0,0.108681,0.641534,1.000000,1.000000,0.618927,1.000000,0.965572,1.000000
612,0.0,0.139787,0.995386,0.795501,0.000000,0.292777,0.000000,0.000000,0.000000,0.611369,...,0.835662,0.0,0.108681,0.641534,1.000000,1.000000,0.618927,1.000000,0.965572,1.000000
613,1.0,1.000000,0.995386,0.255219,1.000000,0.426178,1.000000,1.000000,1.000000,1.000000,...,0.876906,0.0,0.108681,0.776936,0.452714,0.458181,0.209087,0.000000,0.000000,0.256103
614,0.0,0.139787,0.995386,0.795501,0.000000,0.292777,1.000000,0.000000,0.000000,0.611369,...,0.835662,0.0,0.108681,0.776936,0.452714,0.458181,0.209087,0.000000,0.965572,1.000000
615,0.0,0.139787,0.000000,0.795501,0.000000,0.292777,0.604128,0.712529,0.672772,0.611369,...,0.835662,0.0,0.108681,0.776936,0.000000,0.458181,0.209087,0.067361,0.965572,1.000000

In [130]:
X['v1'].max(), X['v1'].min()

(130.798507462687, 128.100242522231)

In [131]:
df_test.head(5)

,Unnamed: 0,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v437,v438,v439,v440,v441,v442,v443,v444,v445,v446
0,0,130.798507,131.174905,129.255102,132.199234,128.746479,130.381148,129.854839,129.828431,129.868526,...,128.800985,128.232694,128.211893,128.167519,126.100000,127.709786,127.349282,127.063052,127.825000,126.611554
1,1,128.100243,128.157072,127.630027,128.273006,130.810403,129.023232,126.769231,126.926295,127.196460,...,128.800985,130.794007,127.750000,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
2,2,128.100243,128.157072,129.255102,128.273006,130.810403,126.042980,129.854839,129.828431,129.868526,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
3,3,130.798507,131.174905,129.255102,132.199234,132.860465,130.381148,129.854839,129.828431,129.868526,...,126.503759,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,127.825000,126.611554
4,4,130.798507,131.174905,129.255102,132.199234,130.810403,130.381148,129.854839,129.828431,129.868526,...,128.914365,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,126.611554

In [132]:
df_test = df_test.drop(columns='Unnamed: 0')
df_test.head(5)

,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,...,v437,v438,v439,v440,v441,v442,v443,v444,v445,v446
0,130.798507,131.174905,129.255102,132.199234,128.746479,130.381148,129.854839,129.828431,129.868526,130.917969,...,128.800985,128.232694,128.211893,128.167519,126.100000,127.709786,127.349282,127.063052,127.825000,126.611554
1,128.100243,128.157072,127.630027,128.273006,130.810403,129.023232,126.769231,126.926295,127.196460,127.433333,...,128.800985,130.794007,127.750000,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
2,128.100243,128.157072,129.255102,128.273006,130.810403,126.042980,129.854839,129.828431,129.868526,128.618063,...,128.800985,130.794007,131.026119,130.512476,130.411160,130.650165,130.904685,131.017268,130.477398,130.496150
3,130.798507,131.174905,129.255102,132.199234,132.860465,130.381148,129.854839,129.828431,129.868526,130.917969,...,126.503759,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,127.825000,126.611554
4,130.798507,131.174905,129.255102,132.199234,130.810403,130.381148,129.854839,129.828431,129.868526,130.917969,...,128.914365,128.232694,128.211893,128.167519,128.051724,127.709786,127.349282,127.063052,125.169118,126.611554

In [133]:
df_test = scaler.fit_transform(df_test)
df_test = pd.DataFrame(data=df_test)
df_test

,0,1,2,3,4,5,6,7,8,9,...,436,437,438,439,440,441,442,443,444,445
0,1.0,1.000000,0.995386,1.000000,0.349839,0.426178,1.000000,1.000000,1.000000,1.000000,...,0.835662,0.0,0.108681,0.377726,0.000000,0.458181,0.209087,0.561484,0.500328,0.256103
1,0.0,0.139787,0.377693,0.795501,0.676015,0.292777,0.000000,0.000000,0.000000,0.411177,...,0.835662,1.0,0.000000,1.000000,1.000000,1.000000,0.618927,1.000000,1.000000,1.000000
2,0.0,0.139787,0.995386,0.795501,0.676015,0.000000,1.000000,1.000000,1.000000,0.611369,...,0.835662,1.0,0.770852,1.000000,1.000000,1.000000,0.618927,1.000000,1.000000,1.000000
3,1.0,1.000000,0.995386,1.000000,1.000000,0.426178,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.0,0.108681,0.377726,0.452714,0.458181,0.209087,0.561484,0.500328,0.256103
4,1.0,1.000000,0.995386,1.000000,0.676015,0.426178,1.000000,1.000000,1.000000,1.000000,...,0.876906,0.0,0.108681,0.377726,0.452714,0.458181,0.209087,0.561484,0.000000,0.256103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,1.0,1.000000,0.995386,0.255219,1.000000,0.426178,1.000000,1.000000,1.000000,1.000000,...,0.876906,0.0,0.108681,0.377726,0.452714,0.458181,0.209087,0.561484,0.500328,0.256103
212,0.0,0.139787,0.000000,0.795501,0.676015,0.292777,0.604128,0.712529,0.672772,0.611369,...,0.835662,0.0,0.108681,0.000000,1.000000,1.000000,0.618927,1.000000,1.000000,1.000000
213,0.0,0.139787,0.995386,0.795501,0.000000,0.292777,0.308130,0.173071,0.086866,0.611369,...,0.876906,0.0,0.108681,0.377726,1.000000,1.000000,0.618927,1.000000,1.000000,1.000000
214,0.0,0.139787,0.995386,0.795501,0.000000,0.000000,1.000000,1.000000,1.000000,0.611369,...,0.876906,0.0,0.108681,0.377726,0.452714,0.458181,0.209087,0.561484,1.000000,1.000000
215,0.0,0.139787,0.377693,0.795501,0.000000,0.292777,1.000000,0.000000,0.000000,0.411177,...,0.835662,1.0,0.770852,1.000000,1.000000,1.000000,0.618927,1.000000,1.000000,1.000000

## Обучаем Log Reg

In [134]:
from sklearn.linear_model import LogisticRegression

In [135]:
model_LR = LogisticRegression().fit(X_scaler, y)
pred = model_LR.predict(df_test)
pred

/Users/muzafarov/anaconda3/envs/ML_OE/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.])

In [137]:
pred = pred.tolist()
pred

[0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0]

In [138]:
df_example

   Unnamed: 0   im
0           0  0.0
1           1  0.0
2           2  1.0
3           3  1.0

In [145]:
d = {'Unnamed: 0': list(range(len(pred))), 'im': pred}
df_answer = pd.DataFrame(data=d)
df_answer

     Unnamed: 0   im
0             0  0.0
1             1  1.0
2             2  0.0
3             3  1.0
4             4  0.0
..          ...  ...
211         211  1.0
212         212  0.0
213         213  1.0
214         214  1.0
215         215  1.0

[216 rows x 2 columns]